/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/spanner/v1/transaction.proto

package com.google.spanner.v1;

public interface NextTransactionTokenOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.spanner.v1.NextTransactionToken)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * An opaque identifier representing the next transaction created in a
   * session.`token` can be passed as the
   * [TransactionOptions.ReadWrite.next_transaction_token] in an
   * [ExecuteSql][google.spanner.v1.Spanner.ExecuteSql] request, allowing a
   * transaction to be both started and committed in a single request when
   * [ExecuteSql.autocommit][google.spanner.v1.Spanner.ExecuteSql.autocommit] is
   * enabled. `token` should only be used before `ttl`. Using `token` post
   * expiration may generate an error.
   * </pre>
   *
   * <code>bytes token = 1;</code>
   *
   * @return The token.
   */
  com.google.protobuf.ByteString getToken();

  /**
   *
   *
   * <pre>
   * Time to live (TTL) of the `token` in milliseconds to be applied by client.
   * `token` is only applicable for the duration specified in `ttl`. 'ttl' will
   * start when the response in received. It can be refreshed on a successful
   * commit.
   * </pre>
   *
   * <code>.google.protobuf.Duration ttl = 2;</code>
   *
   * @return Whether the ttl field is set.
   */
  boolean hasTtl();
  /**
   *
   *
   * <pre>
   * Time to live (TTL) of the `token` in milliseconds to be applied by client.
   * `token` is only applicable for the duration specified in `ttl`. 'ttl' will
   * start when the response in received. It can be refreshed on a successful
   * commit.
   * </pre>
   *
   * <code>.google.protobuf.Duration ttl = 2;</code>
   *
   * @return The ttl.
   */
  com.google.protobuf.Duration getTtl();
  /**
   *
   *
   * <pre>
   * Time to live (TTL) of the `token` in milliseconds to be applied by client.
   * `token` is only applicable for the duration specified in `ttl`. 'ttl' will
   * start when the response in received. It can be refreshed on a successful
   * commit.
   * </pre>
   *
   * <code>.google.protobuf.Duration ttl = 2;</code>
   */
  com.google.protobuf.DurationOrBuilder getTtlOrBuilder();
}
