/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/spanner/v1/transaction.proto

package com.google.spanner.v1;

/**
 *
 *
 * <pre>
 * Next transaction token and TTL applied on the token.
 * </pre>
 *
 * Protobuf type {@code google.spanner.v1.NextTransactionToken}
 */
public final class NextTransactionToken extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.spanner.v1.NextTransactionToken)
    NextTransactionTokenOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use NextTransactionToken.newBuilder() to construct.
  private NextTransactionToken(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private NextTransactionToken() {
    token_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new NextTransactionToken();
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.spanner.v1.TransactionProto
        .internal_static_google_spanner_v1_NextTransactionToken_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.spanner.v1.TransactionProto
        .internal_static_google_spanner_v1_NextTransactionToken_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.spanner.v1.NextTransactionToken.class,
            com.google.spanner.v1.NextTransactionToken.Builder.class);
  }

  public static final int TOKEN_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString token_ = com.google.protobuf.ByteString.EMPTY;
  /**
   *
   *
   * <pre>
   * Token used to identify the transaction to be created next. Used in
   * [BeginTransaction][google.spanner.v1.Spanner.BeginTransaction]
   * [ExecuteSql][google.spanner.v1.Spanner.ExecuteSql] in case of inline begin
   * [Commit][google.spanner.v1.Spanner.Commit] in case of single use transaction
   * </pre>
   *
   * <code>bytes token = 1;</code>
   *
   * @return The token.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getToken() {
    return token_;
  }

  public static final int TTL_MILLIS_FIELD_NUMBER = 2;
  private long ttlMillis_ = 0L;
  /**
   *
   *
   * <pre>
   * Token used to identify the transaction to be created next. Used in
   * [BeginTransaction][google.spanner.v1.Spanner.BeginTransaction]
   * [ExecuteSql][google.spanner.v1.Spanner.ExecuteSql] in case of inline begin
   * [Commit][google.spanner.v1.Spanner.Commit] in case of single use transaction
   * </pre>
   *
   * <code>int64 ttl_millis = 2;</code>
   *
   * @return The ttlMillis.
   */
  @java.lang.Override
  public long getTtlMillis() {
    return ttlMillis_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!token_.isEmpty()) {
      output.writeBytes(1, token_);
    }
    if (ttlMillis_ != 0L) {
      output.writeInt64(2, ttlMillis_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!token_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, token_);
    }
    if (ttlMillis_ != 0L) {
      size += com.google.protobuf.CodedOutputStream.computeInt64Size(2, ttlMillis_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.spanner.v1.NextTransactionToken)) {
      return super.equals(obj);
    }
    com.google.spanner.v1.NextTransactionToken other =
        (com.google.spanner.v1.NextTransactionToken) obj;

    if (!getToken().equals(other.getToken())) return false;
    if (getTtlMillis() != other.getTtlMillis()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    hash = (37 * hash) + TTL_MILLIS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getTtlMillis());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.spanner.v1.NextTransactionToken parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.spanner.v1.NextTransactionToken parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.spanner.v1.NextTransactionToken parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.spanner.v1.NextTransactionToken parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.spanner.v1.NextTransactionToken parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.spanner.v1.NextTransactionToken parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.spanner.v1.NextTransactionToken parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.spanner.v1.NextTransactionToken parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.spanner.v1.NextTransactionToken parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.spanner.v1.NextTransactionToken parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.spanner.v1.NextTransactionToken parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.spanner.v1.NextTransactionToken parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.google.spanner.v1.NextTransactionToken prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * Next transaction token and TTL applied on the token.
   * </pre>
   *
   * Protobuf type {@code google.spanner.v1.NextTransactionToken}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.spanner.v1.NextTransactionToken)
      com.google.spanner.v1.NextTransactionTokenOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.spanner.v1.TransactionProto
          .internal_static_google_spanner_v1_NextTransactionToken_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.spanner.v1.TransactionProto
          .internal_static_google_spanner_v1_NextTransactionToken_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.spanner.v1.NextTransactionToken.class,
              com.google.spanner.v1.NextTransactionToken.Builder.class);
    }

    // Construct using com.google.spanner.v1.NextTransactionToken.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      token_ = com.google.protobuf.ByteString.EMPTY;
      ttlMillis_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.spanner.v1.TransactionProto
          .internal_static_google_spanner_v1_NextTransactionToken_descriptor;
    }

    @java.lang.Override
    public com.google.spanner.v1.NextTransactionToken getDefaultInstanceForType() {
      return com.google.spanner.v1.NextTransactionToken.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.spanner.v1.NextTransactionToken build() {
      com.google.spanner.v1.NextTransactionToken result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.spanner.v1.NextTransactionToken buildPartial() {
      com.google.spanner.v1.NextTransactionToken result =
          new com.google.spanner.v1.NextTransactionToken(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.spanner.v1.NextTransactionToken result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.token_ = token_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ttlMillis_ = ttlMillis_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.spanner.v1.NextTransactionToken) {
        return mergeFrom((com.google.spanner.v1.NextTransactionToken) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.spanner.v1.NextTransactionToken other) {
      if (other == com.google.spanner.v1.NextTransactionToken.getDefaultInstance()) return this;
      if (other.getToken() != com.google.protobuf.ByteString.EMPTY) {
        setToken(other.getToken());
      }
      if (other.getTtlMillis() != 0L) {
        setTtlMillis(other.getTtlMillis());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                token_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
            case 16:
              {
                ttlMillis_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.ByteString token_ = com.google.protobuf.ByteString.EMPTY;
    /**
     *
     *
     * <pre>
     * Token used to identify the transaction to be created next. Used in
     * [BeginTransaction][google.spanner.v1.Spanner.BeginTransaction]
     * [ExecuteSql][google.spanner.v1.Spanner.ExecuteSql] in case of inline begin
     * [Commit][google.spanner.v1.Spanner.Commit] in case of single use transaction
     * </pre>
     *
     * <code>bytes token = 1;</code>
     *
     * @return The token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getToken() {
      return token_;
    }
    /**
     *
     *
     * <pre>
     * Token used to identify the transaction to be created next. Used in
     * [BeginTransaction][google.spanner.v1.Spanner.BeginTransaction]
     * [ExecuteSql][google.spanner.v1.Spanner.ExecuteSql] in case of inline begin
     * [Commit][google.spanner.v1.Spanner.Commit] in case of single use transaction
     * </pre>
     *
     * <code>bytes token = 1;</code>
     *
     * @param value The token to set.
     * @return This builder for chaining.
     */
    public Builder setToken(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      token_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Token used to identify the transaction to be created next. Used in
     * [BeginTransaction][google.spanner.v1.Spanner.BeginTransaction]
     * [ExecuteSql][google.spanner.v1.Spanner.ExecuteSql] in case of inline begin
     * [Commit][google.spanner.v1.Spanner.Commit] in case of single use transaction
     * </pre>
     *
     * <code>bytes token = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearToken() {
      bitField0_ = (bitField0_ & ~0x00000001);
      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }

    private long ttlMillis_;
    /**
     *
     *
     * <pre>
     * Token used to identify the transaction to be created next. Used in
     * [BeginTransaction][google.spanner.v1.Spanner.BeginTransaction]
     * [ExecuteSql][google.spanner.v1.Spanner.ExecuteSql] in case of inline begin
     * [Commit][google.spanner.v1.Spanner.Commit] in case of single use transaction
     * </pre>
     *
     * <code>int64 ttl_millis = 2;</code>
     *
     * @return The ttlMillis.
     */
    @java.lang.Override
    public long getTtlMillis() {
      return ttlMillis_;
    }
    /**
     *
     *
     * <pre>
     * Token used to identify the transaction to be created next. Used in
     * [BeginTransaction][google.spanner.v1.Spanner.BeginTransaction]
     * [ExecuteSql][google.spanner.v1.Spanner.ExecuteSql] in case of inline begin
     * [Commit][google.spanner.v1.Spanner.Commit] in case of single use transaction
     * </pre>
     *
     * <code>int64 ttl_millis = 2;</code>
     *
     * @param value The ttlMillis to set.
     * @return This builder for chaining.
     */
    public Builder setTtlMillis(long value) {

      ttlMillis_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Token used to identify the transaction to be created next. Used in
     * [BeginTransaction][google.spanner.v1.Spanner.BeginTransaction]
     * [ExecuteSql][google.spanner.v1.Spanner.ExecuteSql] in case of inline begin
     * [Commit][google.spanner.v1.Spanner.Commit] in case of single use transaction
     * </pre>
     *
     * <code>int64 ttl_millis = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearTtlMillis() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ttlMillis_ = 0L;
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.spanner.v1.NextTransactionToken)
  }

  // @@protoc_insertion_point(class_scope:google.spanner.v1.NextTransactionToken)
  private static final com.google.spanner.v1.NextTransactionToken DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.spanner.v1.NextTransactionToken();
  }

  public static com.google.spanner.v1.NextTransactionToken getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NextTransactionToken> PARSER =
      new com.google.protobuf.AbstractParser<NextTransactionToken>() {
        @java.lang.Override
        public NextTransactionToken parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<NextTransactionToken> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NextTransactionToken> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.spanner.v1.NextTransactionToken getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
