/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/spanner/v1/transaction.proto

package com.google.spanner.v1;

public interface NextTransactionTokenOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.spanner.v1.NextTransactionToken)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Token used to identify the transaction to be created next. Used in
   * [BeginTransaction][google.spanner.v1.Spanner.BeginTransaction]
   * [ExecuteSql][google.spanner.v1.Spanner.ExecuteSql] in case of inline begin
   * [Commit][google.spanner.v1.Spanner.Commit] in case of single use transaction
   * </pre>
   *
   * <code>bytes token = 1;</code>
   *
   * @return The token.
   */
  com.google.protobuf.ByteString getToken();

  /**
   *
   *
   * <pre>
   * Token used to identify the transaction to be created next. Used in
   * [BeginTransaction][google.spanner.v1.Spanner.BeginTransaction]
   * [ExecuteSql][google.spanner.v1.Spanner.ExecuteSql] in case of inline begin
   * [Commit][google.spanner.v1.Spanner.Commit] in case of single use transaction
   * </pre>
   *
   * <code>int64 ttl_millis = 2;</code>
   *
   * @return The ttlMillis.
   */
  long getTtlMillis();
}
